<img src = "https://img.betapage.co/images/77640967-77641456.png" height=50% width = 50%>

In [2]:
import numpy as np

# Introduction to NumPy

"Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. This library provides you with an array data structure that holds some benefits over Python lists, such as: being more compact, faster access in reading and writing items, being more convenient and more efficient."


# What is a NumPy array?

"The central feature of NumPy is the array object class. Arrays are similar to lists in Python, except that every element of an array must be of the same type, typically a numeric type like float or int. Arrays make operations with large amounts of numeric data very fast and are generally much more efficient than lists."

LINK: https://engineering.ucsb.edu/~shell/che210d/numpy.pdf

<img src = "http://community.datacamp.com.s3.amazonaws.com/community/production/ckeditor_assets/pictures/332/content_arrays-axes.png">

# NumPy Array Syntax
The function array takes two arguments: the list to be converted into the array and the type of each member of the list. 

In [3]:
#List to be converted
lst = [1,2,3,4,5,6,7,8,9]

arr = np.array(lst)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Array elements are accessed, sliced, and manipulated just like lists.

In [4]:
#Index from the 2nd index on
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [5]:
#manipulate item at index 0
arr[0] = 10
arr

array([10,  2,  3,  4,  5,  6,  7,  8,  9])


<b>* Why can't we simply use a python list for these scientific computations?<b>

# Python List VS NumPy Array

"Arrays and lists are both used in Python to store data, but they don't serve exactly the same purposes. They both can be used to store any data type (real numbers, strings, etc), and they both can be indexed and iterated through, but the similarities between the two don't go much further. The main difference between a list and an array is the functions that you can perform to them. For example, you can divide an array by 3, and each number in the array will be divided by 3 and the result will be printed if you request it. If you try to divide a list by 3, Python will tell you that it can't be done, and an error will be thrown."


In [6]:
lst = [3,6,9,12,15,18,12]
lst/3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [7]:
arr = np.array([3,6,9,12,15,18,12])
print(arr * 4)
print(arr)
# note how it can multipy each element easily
# note that it will not change the original array

[12 24 36 48 60 72 48]
[ 3  6  9 12 15 18 12]


Arrays can be multidimensional. Unlike lists, different axes are accessed using commas inside bracket notation. Here is an example with a two-dimensional array (e.g., a matrix)

In [8]:
lst1 = [1,2,3,4,5]
lst2 = [5,6,7,8,9]
arr = np.array([lst2,lst1])
arr
# concatinationg

array([[5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [9]:
(arr/3)
# you can only do this with NumPy

array([[1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667]])

In [10]:
lst_lst = [lst1,lst2]
lst_lst
# you can concatenate two lists in python

[[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]

In [11]:
lst_lst/3
#just can't divide like numpy

TypeError: unsupported operand type(s) for /: 'list' and 'int'

# Indexing Arrays VS Lists

In [ ]:
arr

In [ ]:
arr[0][1]

In [ ]:
lst_lst

In [ ]:
lst_lst[0,1]

In [ ]:
lst_lst[0][1]

In [ ]:
arr[-1]

In [ ]:
lst_lst[-1]

In [ ]:
arr

<h3> How to index a multidemsional array? </h3><br>
The individual elements of arrays can be accessed in the same way as for lists.

<img src = "http://www.scipy-lectures.org/_images/numpy_indexing.png" height = 60% width = 60%>

In [94]:
list_2d = [[0,1,2,3,4,5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]]

In [95]:
myList = [1,2,3]
print(myList)

[1, 2, 3]


In [96]:
array_2d = np.array(list_2d)
print(array_2d)
array_2d.shape

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


(6, 6)

In [97]:
print(array_2d[0,3:5])

[3 4]


In [98]:
print(array_2d[4:,4:])

[[44 45]
 [54 55]]


In [99]:
print(array_2d[:,2])

[ 2 12 22 32 42 52]


In [100]:
print(array_2d[2:5:2,3::2]) # step by 2

[[23 25]
 [43 45]]


In [101]:
# adding new column to numpy array

In [102]:
calc = array_2d[:,5] * 1.05
# new_column = np.array(calc)
print(calc)

[ 5.25 15.75 26.25 36.75 47.25 57.75]


In [103]:
new_array_2d = np.column_stack((array_2d,calc))
print(new_array_2d)

[[ 0.    1.    2.    3.    4.    5.    5.25]
 [10.   11.   12.   13.   14.   15.   15.75]
 [20.   21.   22.   23.   24.   25.   26.25]
 [30.   31.   32.   33.   34.   35.   36.75]
 [40.   41.   42.   43.   44.   45.   47.25]
 [50.   51.   52.   53.   54.   55.   57.75]]


# Changing Array to different DataType

In [ ]:
arr = arr.tolist()
arr

In [ ]:
type(arr)

In [ ]:
arr = np.array(arr)
arr

In [ ]:
type(arr)

In [ ]:
arr.shape

# Change Array Shape

<img src = "https://www.safaribooksonline.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages1346880.png" height = 50% width = 30% style = display.left> 

Transposed versions of arrays can also be generated, which will create a new array with the final two axes switched:

In [ ]:
arr

In [ ]:
arr.shape

In [ ]:
arr.transpose()

In [ ]:
arr.transpose().shape

Make multidimensional array into one-dimensional array

In [ ]:
arr.shape

In [ ]:
arr.flatten()

In [ ]:
arr.flatten().shape

# Create New Array (Specific)

Numpy also provides many functions to create arrays.

Creates an array of all zeros with a specified shape.

In [ ]:
#1-Dimensional
np.zeros(10)

In [ ]:
#2-Dimensional
np.zeros((2,2), int)

Creates an array of all ones with a specified shape.

In [ ]:
#1-Dimensional
np.ones(10, int)

In [ ]:
#2-Dimensional
np.ones((2,2))

Creates a constant array (specified number) with a specified shape.

In [ ]:
#1-Dimensional
np.full(10,7)

In [ ]:
#2-Dimensional
np.full((2, 2), 7)

Created an array of a specified shape with random values.

In [ ]:
#1-Dimensional
np.random.random(10)

In [ ]:
#2-Dimensional
np.random.random((2,2))

Create an array of a specified length with evenly spaced values.

In [ ]:
#1-Dimensional
np.arange(10)

Create an array with a specified "start", "stop", and number of values, evenly spaced.

In [ ]:
#1-Dimensional
np.linspace(1, 10, num = 20)

Creates a 2x2 identity matrix (array).

An identity matrix is a square matrix having 1s on the main diagonal, and 0s everywhere else. These are called identity matrices because, when you multiply them with a compatible matrix , you get back the same matrix.
http://www.sparknotes.com/math/algebra2/matrices/section3.rhtml

In [ ]:
#2-Dimensional
np.eye(10)

OR

In [ ]:
#2-Dimensional
np.identity(10)

# Math Functions using NumPy

"As such, it probably won’t surprise you that you can just use +, -, *, / or % to add, subtract, multiply, divide or calculate the remainder of two (or more) arrays. However, a big part of why NumPy is so handy, is because it also has functions to do this. The equivalent functions of the operations that you have seen just now are, respectively, np.add(), np.subtract(), np.multiply(), np.divide() and np.remainder()."

https://www.datacamp.com/community/tutorials/python-numpy-tutorial

In [ ]:
arr = np.ones((10,10))
arr

In [ ]:
np.add(arr,2)

In [ ]:
#OR
arr + 2

In [ ]:
np.multiply(arr,2)

In [ ]:
#OR
arr*2

In [ ]:
np.subtract(arr,1)

In [ ]:
#OR
arr -1 

In [ ]:
np.divide(arr,2)

In [ ]:
#OR
arr/2

In [ ]:
np.remainder(arr,1)

In [ ]:
#OR
arr % 1

In [ ]:
arr.sum()

In [ ]:
arr.min()

In [ ]:
arr.max()

In [ ]:
arr.mean()

# <font color = magenta> NumPy Problem 1 </font>
<font color = magenta>
Create the three arrays displayed in the image, below.

<img src = "https://i.stack.imgur.com/ojnFF.jpg">

In [12]:
#Array 1
Array1 = np.zeros((5,3), int)
Array1[0] = 4,6,4
Array1[1] = 1,1,8
Array1[2] = 0,7,5
Array1[3] = 5,3,3
Array1[4] = 8,9,5
print(Array1)

[[4 6 4]
 [1 1 8]
 [0 7 5]
 [5 3 3]
 [8 9 5]]


In [13]:
#Array 2
Array2 = np.zeros((5,3), int)
Array2[0] = 8,8,4
Array2[1] = 3,4,4
Array2[2] = 0,0,9
Array2[3] = 3,7,3
Array2[4] = 3,4,7
print(Array2)


[[8 8 4]
 [3 4 4]
 [0 0 9]
 [3 7 3]
 [3 4 7]]


In [14]:
#Array 3
Array3 = np.zeros((5,3),int)
Array3[0] = 9,5,4
Array3[1] = 7,7,3
Array3[2] = 9,5,9
Array3[3] = 8,7,8
Array3[4] = 5,8,8
print(Array3)

[[9 5 4]
 [7 7 3]
 [9 5 9]
 [8 7 8]
 [5 8 8]]


# <font color = magenta> NumPy Problem 2 </font>
<font color = magenta>
Create a multidimensional array of your dimension choice and fill it random values(not filled manually).

In [15]:
array_random = np.random.random((5,4))
print(array_random)

[[0.68296348 0.53088351 0.36826716 0.31891897]
 [0.03554209 0.91068764 0.67623526 0.52203413]
 [0.26881316 0.43481653 0.19349477 0.69491807]
 [0.91953088 0.44590251 0.0466788  0.4350942 ]
 [0.36268347 0.14484379 0.77058789 0.26872117]]


Find the min and max values of your array.

In [16]:
flat_array_random = array_random.flatten()
min(flat_array_random)

0.035542090169800034

# <font color = magenta> NumPy Problem 3 </font>
<font color = magenta>
Create another multidimensional array of your dimension choice and fill it random values(not filled manually). Find the max value of your new array and replace it with your min value. Find the min value and replace it in your array with the max value.

In [36]:
# create array
array_random_2 = np.random.random((6,7))
print("Shape is ", array_random_2.shape)
# find the max value
# flatten
flat_array_random_2 = array_random_2.flatten()
print("flattened shape is ", flat_array_random_2.shape)
max_value = max(flat_array_random_2)
print("max value is ", max_value)
# find location of value
max_location = np.where(flat_array_random_2==max_value)
# find min value
print("index ", max_location, " is where max value ", max_value, " is.")
# find min value
min_value = min(flat_array_random_2)
# find location of min value
min_location = np.where(flat_array_random_2==min_value)
print("index ", min_location, " is where min value ", min_value, " is.")

# replace max value with min value
# set min location with max value
flat_array_random_2[min_location] = max_value
# set max location with min value
flat_array_random_2[max_location] = min_value
print("position ", min_location, " is now ", flat_array_random_2[min_location])
print("position ", max_location, " is now ", flat_array_random_2[max_location])
# put back in original shape
array_random_3 = np.reshape(array_random_2,(6,7))
print("reshaped array is ", array_random_3.shape)


Shape is  (6, 7)
flattened shape is  (42,)
max value is  0.9851556640137878
index  (array([24], dtype=int64),)  is where max value  0.9851556640137878  is.
index  (array([20], dtype=int64),)  is where min value  0.012677136754995821  is.
position  (array([20], dtype=int64),)  is now  [0.98515566]
position  (array([24], dtype=int64),)  is now  [0.01267714]
reshaped array is  (6, 7)


# <font color = magenta> NumPy Problem 4 </font>

Create a random vector of size 10 and sort it.

In [44]:
# create random vector of size 10
random_vector = np.random.random(10,)
print(random_vector)
# sort it
sorted_random_vector = np.sort(random_vector)
print(sorted_random_vector)

[0.45203274 0.51295155 0.93883144 0.82171982 0.16017315 0.76688061
 0.48932709 0.3220696  0.04836073 0.55929395]
[0.04836073 0.16017315 0.3220696  0.45203274 0.48932709 0.51295155
 0.55929395 0.76688061 0.82171982 0.93883144]


# <font color = magenta> NumPy Problem 5 </font>

<font color = magenta>
How to swap two rows of an array?

# Numpy with Bay Area housing data set

In [ ]:
def read_file_housing(filename):
    file_open = open(filename,"r")
    fixed_file = open("fixed-housing-data.csv","w")
    line_count = 0
    for line in iter(file_open):
        line_count += 1
        if "HomeID" in line:
            continue
        line_no_newline = line.rstrip()
        line1 = line_no_newline.replace("84085","94085") #Ex9
        line2 = line1.replace("84087","94087") #Ex9
        line3 = line2.replace("85014","95014") #Ex9
        line4 = line3.replace("85051","95051") #Ex9
        line5 = line4.replace("l","1") #Ex11 -- Car_Garage
        line_split = line5.split(",")
        if (int(line_split[5]) < 100): #Ex10 -- School_API
            line_split[5] = int(line_split[5]) * 10
        else:
            line_split[5] = int(line_split[5])
        line_split = [str(x) for x in line_split]
        myString = ",".join(line_split) + "\n"
        fixed_file.write(myString)
    return

In [ ]:
read_file_housing("bayarea_home_prices.csv")

In [45]:
import numpy as np

In [46]:
"""
0 = HomeID
1 = HomeAge
2 = HomeSqft
3 = LotSize
4 = BedRooms
5 = HighSchoolAPI
6 = ProxFwy
7 = CarGarage
8 = ZipCode
9 = HomePriceK
"""

'\n0 = HomeID\n1 = HomeAge\n2 = HomeSqft\n3 = LotSize\n4 = BedRooms\n5 = HighSchoolAPI\n6 = ProxFwy\n7 = CarGarage\n8 = ZipCode\n9 = HomePriceK\n'

In [47]:
housing = np.loadtxt("fixed-housing-data.csv",
                          dtype=int,
                          delimiter=",")

In [85]:
print(housing[0:2])

[[    1    24  1757  6056     2   899     3     3 94085   894]
 [    2    10  1563  6085     2   959     4     3 94085   861]]


In [51]:
print(housing.shape)

(100, 10)


In [52]:
# home prices
print(housing[:,9])

[ 894  861  831  809  890  867  843  820  874  885  903  912  933  865
  918  950  882  896  942  859  904  912  916  972  908  934  914  949
  919  953  991 1049 1042  994 1030 1019 1044 1038 1024  976 1115 1128
 1071 1059 1000 1185 1015 1114 1138 1068 1068 1097 1074 1114 1075 1130
 1116 1103 1080 1150 1177 1149 1163 1132 1138 1199 1179 1173 1128 1165
 1233 1180 1240 1242 1184 1173 1194 1181 1190 1182 1221 1288 1275 1300
 1272 1294 1219 1282 1256 1205 1252 1294 1269 1335 1267 1307 1336 1284
 1269 1250]


In [53]:
print(housing[:,9] + 10)

[ 904  871  841  819  900  877  853  830  884  895  913  922  943  875
  928  960  892  906  952  869  914  922  926  982  918  944  924  959
  929  963 1001 1059 1052 1004 1040 1029 1054 1048 1034  986 1125 1138
 1081 1069 1010 1195 1025 1124 1148 1078 1078 1107 1084 1124 1085 1140
 1126 1113 1090 1160 1187 1159 1173 1142 1148 1209 1189 1183 1138 1175
 1243 1190 1250 1252 1194 1183 1204 1191 1200 1192 1231 1298 1285 1310
 1282 1304 1229 1292 1266 1215 1262 1304 1279 1345 1277 1317 1346 1294
 1279 1260]


In [54]:
print(housing.sum(axis=0)) # sum by columns

[   5050    1720  161528  784050     271   90443     310     152 9455925
  108099]


In [55]:
print(housing.sum(axis=1)) # sum by rows

[103724 103574 103240 103224 103896 103638 104044 103869 103609 104170
 104094 103592 103978 104376 104062 105595 104218 104335 104940 104012
 104075 104583 104684 105583 104958 104446 104876 105593 104503 106006
 105990 106058 106256 105929 106298 105629 106320 106196 106023 106261
 105369 105445 106369 105987 105936 105549 106606 105320 105358 106782
 106365 106479 106225 105461 106713 105795 106138 105594 106827 105847
 105796 106180 105869 105800 106169 107018 106669 106315 106430 106551
 107465 106524 107181 107608 106533 107139 107961 106805 106554 106595
 107843 107864 108077 107983 108182 108227 107735 107879 108478 108106
 107902 108487 107956 108654 108172 108678 108406 108111 108617 108407]


In [56]:
homes_94085 = (housing[:,8] == 94085) # grabs all homes in zip 94085 and puts them in homes_94085 - it's true or false values

In [57]:
print(homes_94085)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True False  True  True  True  True False
  True  True  True False  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False]


In [58]:
data_94085 = housing[homes_94085,][:,:]
print(data_94085)

[[    1    24  1757  6056     2   899     3     3 94085   894]
 [    2    10  1563  6085     2   959     4     3 94085   861]
 [    3    14  1344  6089     2   865     4     3 94085   831]
 [    4    14  1215  6129     3   959     4     2 94085   809]
 [    5    24  1866  6141     3   877     4     1 94085   890]
 [    6    18  1589  6148     2   920     3     0 94085   867]
 [    7    13  1947  6183     3   959     3     1 94085   843]
 [    8    19  1839  6186     3   905     4     0 94085   820]
 [    9    17  1501  6233     2   884     3     1 94085   874]
 [   10    24  1933  6276     2   950     4     1 94085   885]
 [   11    12  1798  6346     3   931     3     2 94085   903]
 [   12    22  1221  6430     3   904     2     1 94085   912]
 [   13    15  1541  6514     2   872     2     1 94085   933]
 [   14    25  1974  6547     2   857     4     3 94085   865]
 [   15    10  1510  6633     2   884     3     2 94085   918]
 [   17    23  1464  6773     3   965     4     2 94085

In [59]:
sum_price_94085 = data_94085[:,9].sum()

In [60]:
print(len(data_94085))

25


In [61]:
print(data_94085.shape[0]) # shape[0] is rows

25


In [62]:
print(data_94085.shape[1]) # shope[1] is columns

10


In [63]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [64]:
average_94085 = sum_price_94085/25
print(average_94085)

885.96


# NumPy Problem 6
### Calculate average price in each zip code: 94085, 94087, 95014, 95051
### Calculate minimum and max price in each zip code: 94085, 94087, 95014, 95051
### Calculate standard deviation of price in each zip code: 94085, 94087, 95014, 95051

In [79]:
# Your code here
# create a array for boolean values of 94085
homes_94085 = (housing[:,8] == 94085) # grabs all homes in zip 94085 and puts them in homes_94085 - it's true or false values
# create an array of housing data for 94085
data_94085 = housing[homes_94085,][:,:]
# find sum of column 9 which is house pricing
sum_price_94085 = data_94085[:,9].sum()
# find average by dividing by number of rows
avg_price_94085 = sum_price_94085/(data_94085.shape[0])
print("The average price of zip 94085 is ", avg_price_94085)

The average price of zip 94085 is  885.96


In [80]:
h1 = housing[housing[:,5].argsort()] # by school_api ascending
print(h1)

[[   65    14  1617  8394     2   850     2     0 94087  1138]
 [   73    25  1302  8668     3   850     4     2 95014  1240]
 [   23    15  1828  6956     3   851     4     3 94085   916]
 [   20    13  1358  6819     2   851     3     2 94085   859]
 [   79    17  1373  8953     2   851     2     0 94087  1190]
 [   77    17  1881  8921     3   852     2     0 95014  1194]
 [   19    10  1246  6810     2   853     4     3 95051   942]
 [   32    18  1866  7181     2   854     2     3 95051  1049]
 [   95    13  1582  9339     3   856     3     0 95014  1267]
 [   26    12  1500  7025     2   856     4     2 94085   934]
 [   99    19  1880  9470     3   857     3     3 95014  1269]
 [   53    23  1289  7873     2   857     3     0 95051  1074]
 [   67    24  1947  8502     2   857     4     0 94087  1179]
 [  100    11  1691  9476     4   857     4     0 95014  1250]
 [   14    25  1974  6547     2   857     4     3 94085   865]
 [   44    11  1415  7541     3   859     4     0 95051

In [81]:
h2 = housing[housing[:,5].argsort()[::-1]] # by school_api descending
print(h2)

[[   38    22  1724  7339     3   975     3     3 95051  1038]
 [   35    12  1943  7249     2   974     2     0 95051  1030]
 [   27    13  1836  7027     2   966     3     3 94085   914]
 [   17    23  1464  6773     3   965     4     2 94085   882]
 [   69    21  1575  8579     2   962     4     3 94087  1128]
 [   37    13  1874  7333     3   960     3     2 95051  1044]
 [   45    15  1249  7609     3   960     2     2 95051  1000]
 [    2    10  1563  6085     2   959     4     3 94085   861]
 [    4    14  1215  6129     3   959     4     2 94085   809]
 [   33    11  1953  7199     3   959     3     2 95051  1042]
 [    7    13  1947  6183     3   959     3     1 94085   843]
 [   76    12  1947  8882     3   954     3     2 94087  1173]
 [   59    22  1559  8096     2   953     2     3 95051  1080]
 [   57    11  1927  7983     3   950     3     1 94087  1116]
 [   10    24  1933  6276     2   950     4     1 94085   885]
 [   50    19  1836  7803     3   949     3     0 95051

# NumPy Problem 7
### Find top-2 listings by School API for all zipcodes

In [86]:
# Your code here
# use h2 that has it in decending order
# display index 0 and 1
print(h2[0:2])

[[   38    22  1724  7339     3   975     3     3 95051  1038]
 [   35    12  1943  7249     2   974     2     0 95051  1030]]


# NumPy Problem 8
### Prices are expected to go up by 4% next year.
### Add another column with predicted prices

In [135]:
# Your code here
# use housing data
# print(housing[:,9])
# create an array of increased housing value
next_year_price = housing[:,9]*1.04
#print(next_year_price[1])
#h4 = housing
# put both arrays together housing and next_year_price
# sample
h4 = np.column_stack((housing,next_year_price))
print(h4) # not sure why the format looks weird

[[1.00000e+00 2.40000e+01 1.75700e+03 ... 9.40850e+04 8.94000e+02
  9.29760e+02]
 [2.00000e+00 1.00000e+01 1.56300e+03 ... 9.40850e+04 8.61000e+02
  8.95440e+02]
 [3.00000e+00 1.40000e+01 1.34400e+03 ... 9.40850e+04 8.31000e+02
  8.64240e+02]
 ...
 [9.80000e+01 2.10000e+01 1.31200e+03 ... 9.50140e+04 1.28400e+03
  1.33536e+03]
 [9.90000e+01 1.90000e+01 1.88000e+03 ... 9.50140e+04 1.26900e+03
  1.31976e+03]
 [1.00000e+02 1.10000e+01 1.69100e+03 ... 9.50140e+04 1.25000e+03
  1.30000e+03]]


# NumPy Problem 9
### Sort the matrix based on home prices. Save the updated numpy matrix with added column in Problem 8 to a file.

In [136]:
# Your code here
h5 = h4[h4[:,9].argsort()] # by school_api ascending
print(h5)

[[4.00000e+00 1.40000e+01 1.21500e+03 ... 9.40850e+04 8.09000e+02
  8.41360e+02]
 [8.00000e+00 1.90000e+01 1.83900e+03 ... 9.40850e+04 8.20000e+02
  8.52800e+02]
 [3.00000e+00 1.40000e+01 1.34400e+03 ... 9.40850e+04 8.31000e+02
  8.64240e+02]
 ...
 [9.60000e+01 1.10000e+01 1.98100e+03 ... 9.50140e+04 1.30700e+03
  1.35928e+03]
 [9.40000e+01 2.10000e+01 1.98300e+03 ... 9.50140e+04 1.33500e+03
  1.38840e+03]
 [9.70000e+01 1.00000e+01 1.64500e+03 ... 9.50140e+04 1.33600e+03
  1.38944e+03]]


# <font color = magenta> NumPy Problem 10 </font>

Write a function that takes a long string containing multiple words. Print the same string, except with the words in backwards order. 

<i>HINT: Use <b>YOUR_STRING<code>.split()</code></b> function<br></i>

In [121]:
myString = "Python for Data Science class is on Saturdays for seven weeks." # use split, join, reverse - these are used frequently
mySplitString = myString.split()
print(mySplitString)
type(mySplitString)
# create an empty list
myReverseList = []
for i in reversed(mySplitString):
    myReverseList.append(i)
print(myReverseList)

['Python', 'for', 'Data', 'Science', 'class', 'is', 'on', 'Saturdays', 'for', 'seven', 'weeks.']
['weeks.', 'seven', 'for', 'Saturdays', 'on', 'is', 'class', 'Science', 'Data', 'for', 'Python']
